#!/bin/sh
#
# mibctlInit - initialization script for mibctl
#
# Copyright (c) 2007, TeamF1, Inc.
#
# modification history
# --------------------
# 01a,01jun07,rks written


if [ "$INCLUDE_MIBCTL" = "y" ]; then

MODULES_DIR=$MIBCTL_INSTALL_PATH/lib/modules/mibctl/

insmod $MODULES_DIR/mibctl.*

fi
